// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AircraftForSale
{
	public partial class MainRegistrationViewController : UITableViewController
	{
		public MainRegistrationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
