// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AircraftForSale
{
	public partial class MessageViewController : UIViewController
	{
        void CloseButton_TouchUpInside(object sender, EventArgs e)
        {
            DismissModalViewController(true);
        }


		public MessageViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {

        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            CloseButton.TouchUpInside += CloseButton_TouchUpInside;

        }

        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);
            CloseButton.TouchUpInside -= CloseButton_TouchUpInside;
        }

    }
}
