// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AircraftForSale
{
	public partial class RegistrationViewController : UIViewController
	{
		public RegistrationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
