// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AircraftForSale
{
	public partial class SplashVideoViewController : UIViewController
	{
		public SplashVideoViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
