// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AircraftForSale
{
	public partial class WelcomeBackViewController : UIViewController
	{
        void CloseButton_TouchUpInside(object sender, EventArgs e)
        {
            DismissModalViewController(true);
        }

        void EmailSupport_TouchUpInside(object sender, EventArgs e)
        {
            ContactWebViewController contactWebViewController = (ContactWebViewController)Storyboard.InstantiateViewController("ContactWebViewController");
            contactWebViewController.isModal = true;
            this.PresentViewController(contactWebViewController, true, null);
        }


        public WelcomeBackViewController(IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            //    view.backgroundColor = UIColor.clearColor()
            //view.opaque = false
            View.BackgroundColor = UIColor.Clear;
            View.Opaque = false;

            BackgroundView.Layer.CornerRadius = 25;
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            CloseButton.TouchUpInside += CloseButton_TouchUpInside;
            tryAgainButton.TouchUpInside += CloseButton_TouchUpInside;
            emailSupportButton.TouchUpInside += EmailSupport_TouchUpInside;

        }

        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);
            CloseButton.TouchUpInside -= CloseButton_TouchUpInside;
            tryAgainButton.TouchUpInside -= CloseButton_TouchUpInside;
            emailSupportButton.TouchUpInside -= EmailSupport_TouchUpInside;
        }

    }
}
